// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwjpC1f52i5F2ftpdnciUdKDQIHLU1Cg',
    appId: '1:908192292141:android:d7e5a8b044b37cd84647a4',
    messagingSenderId: '908192292141',
    projectId: 'flutterexcelerate-13d2f',
    storageBucket: 'flutterexcelerate-13d2f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW3Oc6oCuQxt7ra31v0zegIjEFCyO0A50',
    appId: '1:908192292141:ios:380445f4e011ee9c4647a4',
    messagingSenderId: '908192292141',
    projectId: 'flutterexcelerate-13d2f',
    storageBucket: 'flutterexcelerate-13d2f.firebasestorage.app',
    androidClientId: '908192292141-hcr2cu8uld30qt0r5kpjjomdgm9ic3h0.apps.googleusercontent.com',
    iosClientId: '908192292141-k0n5c1kkuell6j1ug4pjpfncjhr641ta.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterExcelerateFrontend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIxtAY-wHZ_YIoGO-NYcnGQXIGObUKII',
    appId: '1:908192292141:web:7c8cab2053354c924647a4',
    messagingSenderId: '908192292141',
    projectId: 'flutterexcelerate-13d2f',
    authDomain: 'flutterexcelerate-13d2f.firebaseapp.com',
    storageBucket: 'flutterexcelerate-13d2f.firebasestorage.app',
    measurementId: 'G-045VKY0VMK',
  );
}
